import 'en.dart';

class Fr implements En {
  @override
  Direction $direction = Direction.ltr;
  @override
  String $name = "Français";
  @override
  String $code = "fr";

  @override
  Map<String, String> dictionary = {
    // common
    "cancel": "Annuler",
    "close": "Fermer",
    "save": "Enregistrer",
    "reset": "Réinitialiser",
    "continue": "Continuer",
    "add": "Ajouter",
    "edit": "Modifier",
    "delete": "Supprimer",
    "archive": "Archiver",
    "restore": "Restaurer",
    "logout": "Déconnexion",
    "noResultsFound": "Aucun résultat trouvé",
    "startTyping": "Commencez à taper",
    "home": "Accueil",
    "calendar": "Calendrier",
    "gettingImages": "Récupération des images",

    // call
    "callLaboratory": "Appeler le laboratoire",
    "callPatient": "Appeler le patient",
    "emailDoctor": "Envoyer un e-mail au médecin",
    "callIssuer": "Appeler l'émetteur",

    // screens
    "settings": "Paramètres",
    "dashboard": "Tableau de bord",
    "appointments": "Rendez-vous",
    "patients": "Patients",
    "doctors": "Médecins",
    "labworks": "Travaux de labo",
    "statistics": "Statistiques",

    // dashboard
    "admin": "Administrateur",
    "fullStats": "Statistiques complètes",
    "payments": "Paiements",
    "appointmentsToday": "Rendez-vous aujourd'hui",
    "patientsToday": "Patients aujourd'hui",
    "newPatientsToday": "Nouveaux patients aujourd'hui",
    "paymentsMadeToday": "Paiements effectués aujourd'hui",
    "modeAdmin": "ADMIN",
    "modeUser": "UTILISATEUR",
    "modeOffline": "HORS LIGNE",
    "onceConnectionIsStable":
        "Une fois votre connexion stable, vous pouvez utiliser le bouton en haut à droite pour vous reconnecter.",
    "unRestrictedAccess": "accès illimité dans l'application",
    "restrictedAccess":
        "accès restreint à certains écrans selon les instructions de l'administrateur",
    "youAreCurrentlyIn": "Vous êtes actuellement en",
    "mode": "mode",
    "youHave": "Vous avez",
    "hello": "Bonjour",

    // datatable
    "archiveSelected": "Archiver la sélection",
    "searchPlaceholder": "Rechercher...",
    "showHideArchived": "Afficher/Masquer les archivés",
    "showing": "Affichage",
    "showMore": "Afficher plus",
    "by": "Par",
    "byTitle": "Par titre",
    "byDate": "Par date",
    "noItemsFound": "Aucun élément trouvé",
    "filter": "Filtrer",

    // doctors
    "doctor": "Médecin",
    "newDoctor": "Nouveau médecin",
    "doctorDetails": "Détails du médecin",
    "pastAppointments": "Rendez-vous passés",
    "upcomingAppointments": "Prochains rendez-vous",
    "doctorName": "Nom du médecin",
    "doctorEmail": "E-mail du médecin",
    "dutyDays": "Jours de service",
    "addAppointment": "Ajouter un rendez-vous",
    "lockToUsers":
        "Seuls les utilisateurs suivants peuvent consulter/modifier les données et rendez-vous de ce médecin",
    "noUpcomingAppointmentsForThisDoctor":
        "Aucun rendez-vous à venir trouvé. Utilisez le bouton ci-dessous pour en enregistrer un nouveau",

    // days and months
    "monday": "Lundi",
    "tuesday": "Mardi",
    "wednesday": "Mercredi",
    "thursday": "Jeudi",
    "friday": "Vendredi",
    "saturday": "Samedi",
    "sunday": "Dimanche",
    "january": "Janvier",
    "february": "Février",
    "march": "Mars",
    "april": "Avril",
    "may": "Mai",
    "june": "Juin",
    "july": "Juillet",
    "august": "Août",
    "september": "Septembre",
    "october": "Octobre",
    "november": "Novembre",
    "december": "Décembre",

    // appointment card
    "appointment": "Rendez-vous",
    "patient": "Patient",
    "photos": "Photos",
    "pre-opNotes": "Notes préopératoires",
    "post-opNotes": "Notes postopératoires",
    "prescription": "Ordonnance",
    "pay": "Payer",
    "paid": "Payé",
    "price": "Prix",
    "underpaid": "Sous-payé",
    "overpaid": "Surpayé",
    "fullyPaid": "Entièrement payé",
    "includesOtherAppointments":
        "Ce total reflète également les paiements d'autres rendez-vous.",
    "paymentSummary": "Récapitulatif des paiements",
    "editingAppointment": "Modification du rendez-vous",
    "after": "Après",
    "days": "jours",
    "day": "jour",
    "isDone": "Le rendez-vous est terminé",
    "addLabwork": "Ajouter un travail de laboratoire pour ce rendez-vous",
    "labworksForThisAppointment": "Travaux de laboratoire pour ce rendez-vous",

    // patients
    "patientDetails": "Détails du patient",
    "age": "Âge",
    "gender": "Sexe",
    "lastVisit": "Dernière visite",
    "totalPayments": "Total des paiements",
    "daysAgo": "jours passés",
    "noVisits": "Aucune visite",
    "addNewPatient": "Ajouter un nouveau patient",
    "name": "Nom",
    "birthYear": "Année de naissance",
    "phone": "Téléphone",
    "email": "E-mail",
    "address": "Adresse",
    "notes": "Notes",
    "patientTags": "Étiquettes du patient",
    "male": "Masculin",
    "female": "Féminin",
    "noAppointmentsFound":
        "Aucun rendez-vous trouvé pour ce patient, utilisez le bouton ci-dessous pour ajouter un nouveau rendez-vous.",
    "editPatient": "Modifier le patient",
    "editAppointment": "Modifier le rendez-vous",
    "patientPage": "Page web du patient",
    "patientCanUseTheFollowing":
        "Le patient peut utiliser le lien suivant pour accéder à ses rendez-vous, paiements et photos.",
    "web": "Web",
    "telegram": "Telegram",
    "printQR": "Imprimer le code QR",
    "dentalNotes": "Notes dentaires",
    "showPrimary": "Afficher la dentition temporaire",
    "showPermanent": "Afficher la dentition permanente",
    "primary": "Temporaire",
    "permanent": "Permanente",
    "lower": "Inférieur",
    "upper": "Supérieur",
    "left": "Gauche",
    "right": "Droite",
    "centralIncisor": "Incisive centrale",
    "lateralIncisor": "Incisive latérale",
    "canine": "Canine",
    "firstPremolar": "Première prémolaire",
    "secondPremolar": "Deuxième prémolaire",
    "firstMolar": "Première molaire",
    "secondMolar": "Deuxième molaire",
    "thirdMolar": "Troisième molaire",
    "exportSelected": "Exporter la sélection",
    "noPatientsSelected": "Aucun patient sélectionné",

    // communication
    "contact": "Contact",
    "sendEmail": "Envoyer un e-mail",
    "whatsapp": "WhatsApp",
    "call": "Appeler",
    "text": "Message",
    "countryCode": "Code de pays",
    "countryCode_desc":
        "Sélectionnez le code de pays par défaut lors des appels ou de l'envoi de messages",

    // treatments
    "treatment": "Traitement",
    "allTreatments": "Tous les traitements",
    "extraction": "Extraction",
    "filling": "Obturation",
    "pulpotomy": "Pulpotomie",
    "rCT": "Traitement de canal",
    "re-RCT": "Retraitement de canal",
    "ortho": "Orthodontie",
    "whitening": "Blanchiment",
    "clean": "Détartrage",
    "implant": "Implant",
    "surgery": "Chirurgie",
    "crown": "Couronne",
    "veneer": "Facette",
    "bridge": "Bridge",
    "overlay": "Overlay",
    "temporary": "Temporaire",
    "tap the treatment you have performed to register it to the tooth":
        "Appuyez sur le traitement effectué pour l'enregistrer sur la dent",
    "tap the condition or history of the tooth to register it":
        "Appuyez sur l'état ou l'historique de la dent pour l'enregistrer",
    "missing": "Absente",
    "caries": "Caries",
    "fractured": "Fracturée",
    "mobility": "Mobilité",
    "recession": "Récession",
    "rroot": "R. Radiculaire",
    "rprimary": "R. Temporaire",
    "malposition": "Malposition",
    "impacted": "Incluse",
    "abutment": "Pilier",
    "pontic": "Pontique",

    // calendar (appointments)
    "allDoctors": "Tous les médecins",
    "noAppointmentsForThisDay": "Aucun rendez-vous pour ce jour",
    "weekAbbr": "S",
    "twoWeeksAbbr": "2S",
    "monthAbbr": "M",
    "today": "Aujourd'hui",
    "newPatient": "Nouveau patient",
    "date": "Date",
    "changeDate": "Modifier la date",
    "changeTime": "Modifier l'heure",
    "attention": "Attention",
    "doctorNotAvailable":
        "L'un des médecins sélectionnés pourrait ne pas être disponible à la date sélectionnée.",
    "time": "Heure",
    "preOperativeNotes": "Notes préopératoires",
    "selectDoctors": "Sélectionner les médecins",
    "selectPatient": "Sélectionner le patient",
    "operativeDetails": "Détails opératoires",
    "postOperativeNotes": "Notes postopératoires",
    "printPrescription": "Imprimer l'ordonnance",
    "priceIn": "Prix en",
    "paidIn": "Payé en",
    "gallery": "Galerie",
    "link": "Lien",
    "upload": "Téléverser",
    "camera": "Appareil photo",
    "emptyGallery": "Galerie vide",
    "noPhotos": "Aucune photo n'a encore été téléversée.",
    "otherPhotos": "Photos d'autres rendez-vous",
    "draw": "Dessiner",
    "erase": "Effacer",
    "showDrawings": "Afficher les dessins",
    "importingPhotosFromLink": "Importation de photos depuis le lien",
    "useThisForm":
        "Utilisez ce formulaire pour importer des photos à partir de liens partagés, comme Google Photos, ou toute page web accessible contenant des photos que vous souhaitez ajouter à ce rendez-vous.",
    "error": "Erreur",
    "enterLink": "Entrez une URL contenant des photos",
    "import": "Importer",

    // labworks
    "laboratory": "Laboratoire",
    "month": "mois",
    "newLabwork": "Nouveau travail de labo",
    "labwork": "travail de labo",
    "labworkTitle": "Titre du travail de labo",
    "orderNotes": "Notes de commande",
    "unpaid": "Non payé",
    "noSuggestions": "Aucune suggestion",
    "received": "Travail reçu du laboratoire",
    "showReceived": "Afficher les reçus",

    // expenses
    "expense": "Dépense",
    "expenses": "Dépenses",
    "receipt": "Reçu",
    "title": "Titre",
    "cost": "Coût",
    "issuer": "Émetteur",
    "amount": "Montant",
    "amountIn": "Montant en",
    "status": "Statut",
    "due": "Dû",
    "open": "Ouvrir",
    "rename": "Renommer",
    "addSupplier": "Ajouter un fournisseur",
    "archiveSupplier": "Archiver le fournisseur",
    "items": "Articles",
    "markAsPaid": "Marquer comme payé",
    "markAsDue": "Marquer comme dû",
    "unpaidOrders": "Commandes non payées",
    "paymentHistory": "Historique des paiements",
    "addOrder": "Ajouter une commande",
    "filterByItems": "Filtrer par articles",

    // notes
    "addColumn": "Ajouter une colonne",
    "editColumn": "Modifier la colonne",
    "columnTitle": "Titre de la colonne",
    "columnColor": "Couleur de la colonne",
    "addNote": "Ajouter une note",
    "editNote": "Modifier la note",
    "note": "Note",
    "recurrence": "Récurrence",
    "isARecurrenceOfOlderNote": "Est une récurrence d'une note plus ancienne",
    "recurringEvery": "Récurrent tous les",
    "recurring": "Récurrent",
    "column": "Colonne",
    "uncategorized": "Non catégorisé",
    "relatingToPatient": "Relatif au patient",
    "assignedTo": "Assigné à",
    "dueDate": "Date d'échéance",
    "attachments": "Pièces jointes",
    "archiveAllCompletedNotes": "Archiver toutes les notes complétées",
    "moveTowardsEnd": "Déplacer vers la fin",
    "moveTowardsStart": "Déplacer vers le début",
    "item": "Article",
    "addAttachment": "Ajouter une pièce jointe",
    "tapToDownload": "Appuyez pour télécharger",
    "addComment": "Ajouter un commentaire",
    "sendComment": "Envoyer le commentaire",
    "tapToMarkAsPending": "Appuyez pour marquer comme en attente",
    "tapToMarkAsDone": "Appuyez pour marquer comme terminé",
    "archived": "Archivé",
    "overdue": "En retard",
    "incoming": "Entrant",
    "outgoing": "Sortant",
    "pending": "En attente",
    "completed": "Terminé",
    "unassigned": "Non assigné",
    "comments": "Commentaires",
    "createdDate": "Date de création",
    "changeDueDate": "Modifier la date d'échéance",
    "createdBy": "Créé par",
    "switchAssignee": "Changer l'assigné",
    "noAssignee": "Aucun assigné",
    "sort": "Trier",
    "ascending": "croissant",
    "descending": "décroissant",
    "showAll": "Tout afficher",
    "showOnlyMine": "Afficher uniquement les miens",
    "allAccounts": "Tous les comptes",

    // stats
    "pickRange": "Sélectionner une plage",
    "start": "Début",
    "end": "Fin",
    "weeks": "Semaines",
    "months": "Mois",
    "quarters": "Trimestres",
    "years": "Années",
    "appointmentsPer": "Rendez-vous par",
    "paymentsAndExpensesPer": "Paiements et dépenses par",
    "newPatientsPer": "Nouveaux patients par",
    "doneMissedPer": "Effectués et manqués par",
    "timeOfDay": "Heure du jour",
    "dayOfWeek": "Jour de la semaine",
    "dayOfMonth": "Jour du mois",
    "monthOfYear": "Mois de l'année",
    "patientsGender": "Sexe des patients",
    "total": "Total",
    "in_Duration_": "en",
    "acquiredPatientsIn": "Patients acquis en",
    "doneAndMissedAppointmentsIn": "Rendez-vous effectués et manqués en",
    "distributionOfAppointments": "Répartition des rendez-vous",
    "maleAndFemalePatients": "Patients masculins et féminins",
    "done": "effectué",
    "missed": "manqué",

    // settings
    "currency": "Devise",
    "currency_desc":
        "Code de devise à utiliser dans toute l'application (ex. USD, EUR, DZD).",
    "phone_desc":
        "Le numéro de téléphone sera affiché dans les impressions et sur la page web du patient.",
    "prescriptionFooter": "Pied de page de l'ordonnance",
    "prescriptionFooter_desc":
        "Ce texte sera affiché en bas de l'ordonnance.",
    "language": "Langue",
    "language_desc":
        "La langue de l'interface pour les menus, boutons et informations utilisés dans l'application.",
    "startingDayOfWeek": "Premier jour de la semaine",
    "startingDayOfWeek_desc":
        "Le jour de la semaine par lequel commence la semaine.",
    "dateFormat": "Format de date",
    "dateFormat_desc": "Ce format sera utilisé pour afficher les dates.",
    "cacheReset": "Réinitialisation du cache",
    "cacheReset_desc":
        "Vous pouvez utiliser le bouton ci-dessous pour supprimer les données sauvegardées localement (sauf les images), cela pourrait résoudre certains problèmes de synchronisation.",
    "month/day/year": "Mois/Jour/Année",
    "day/month/year": "Jour/Mois/Année",
    "appliesTo": "S'applique à",
    "all": "Tous",
    "you": "vous",
    "initialSynchronization": "Synchronisation initiale",
    "synchronizing": "Synchronisation",
    "clearingLocalData": "Suppression des données locales",
    "dentalNotation": "Notation dentaire",
    "dentalNotation_desc": "Choisissez votre système de notation préféré",
    "palmer": "Palmer",
    "universal": "Universal",
    "ISO": "ISO",

    // advanced settings: Backups
    "backups": "Sauvegardes",
    "refresh": "Actualiser",
    "download": "Télécharger",
    "createNew": "Créer nouveau",
    "restoreBackup": "Restaurer la sauvegarde",
    "restoreBackupWarning1":
        "La restauration de cette sauvegarde écrasera toutes les données actuelles dans l'application. Toutes les modifications effectuées après la date de cette sauvegarde",
    "restoreBackupWarning2":
        "seront perdues.\n\nÊtes-vous sûr de vouloir restaurer cette sauvegarde ?",
    "sureDeleteBackup":
        "Êtes-vous sûr de vouloir supprimer cette sauvegarde ?",
    "backupDate": "Date de la sauvegarde",
    "useTheFollowingLinkToDownloadTheBackup":
        "Utilisez le lien suivant pour télécharger la sauvegarde",

    // advanced settings: Admins
    "admins": "Administrateurs",
    "accountCreated": "Compte créé",
    "editAdmin": "Modifier l'administrateur",
    "validEmailMustBeProvided":
        "Une adresse e-mail valide doit être fournie",
    "password": "Mot de passe",
    "leaveBlankToKeepUnchanged": "Laisser vide pour ne pas modifier",
    "updatingPassword": "Mise à jour du mot de passe",
    "leaveItEmpty":
        "Laissez le champ mot de passe vide si vous ne souhaitez pas le modifier.",
    "newAdmin": "Nouvel administrateur",
    "minimumPasswordLength": "Mot de passe d'au moins 10 caractères",

    // advanced settings: Users
    "users": "Utilisateurs",
    "editUser": "Modifier l'utilisateur",
    "newUser": "Nouvel utilisateur",

    // advanced settings: Permissions
    "permissions": "Permissions des utilisateurs",
    "usersCanAccess": "Les utilisateurs peuvent accéder",
    "permissionsNotice":
        "Les permissions suivantes s'appliquent aux utilisateurs listés ci-dessus et à l'accès hors ligne. Cependant, les administrateurs comme vous ont un accès illimité dans l'application, sauf en mode hors ligne.",
    "restricted": "Restreint",
    "personal": "Personnel",
    "full": "Complet",
    "view": "Voir",
    "local": "local",
    "canUpload": "Peut téléverser",
    "cantUpload": "Ne peut pas téléverser",
    "accounts": "Comptes",
    "operatesOnPatients": "Opère sur les patients",
    "undelivered": "non livré",

    // advanced settings: prod tests
    "prodTests": "Tests de production",
    "fileStorageTest": "Test de stockage de fichiers",
    "fileStorageTestDesc":
        "Utilisez le bouton suivant pour tester si le stockage S3 fonctionne correctement.",
    "fileStorageButton": "Tester la configuration S3",
    "fileStorageFail": "La configuration S3 a échoué",
    "fileStorageSuccess": "La configuration S3 fonctionne correctement",
    "emailTest": "Test d'e-mail",
    "emailTestDesc":
        "Utilisez le bouton suivant pour tester si votre serveur peut envoyer des e-mails correctement. Un e-mail similaire à une réinitialisation de mot de passe devrait être envoyé à l'adresse e-mail cible.",
    "targetEmail": "E-mail cible",
    "emailTestButton": "Envoyer un e-mail de test",
    "emailTestFail": "Le test d'e-mail a échoué",
    "emailTestSuccess":
        "E-mail envoyé avec succès, veuillez vérifier votre boîte de réception.",
    "fail": "Échec",
    "success": "Succès",

    // login
    "login": "Connexion",
    "resetPassword": "Réinitialiser le mot de passe",
    "serverUrl": "URL du serveur",
    "proceedOffline": "Continuer hors ligne",
    "youLLGet": "Recevoir le lien de réinitialisation par e-mail",
    "beenSent":
        "Les instructions de réinitialisation du mot de passe vous ont été envoyées, vérifiez votre boîte de réception.",

    // static notifications flyout
    "notifications": "Notifications",
    "enableNotifications": "Activer les notifications",
    "dueLabworks": "Travaux de labo en attente",
    "undeliveredLabworks": "Travaux de labo non livrés",
    "outgoingNotes": "Notes sortantes",
    "incomingNotes": "Notes entrantes",
    "appointmentsSetToday": "rendez-vous aujourd'hui",
    "labworksDue": "travaux de labo en attente",
    "labworksNotDelivered": "travaux de labo non livrés",
    "outgoingPendingNotes": "notes sortantes en attente",
    "incomingPendingNotes": "notes entrantes en attente",

    // other
    "otherNotesPerAppointment":
        "D'autres notes enregistrées dans le panneau de rendez-vous n'apparaissent pas ici.",
    "sureArchiveSelected":
        "Êtes-vous sûr de vouloir archiver les éléments sélectionnés ?",
    "sureClosePanel":
        "Êtes-vous sûr de vouloir fermer ce panneau ? Toutes les modifications non enregistrées seront perdues.",
    "sure": "Sûr",
    "back": "Retour",
    "firstLaunchDialogTitle": "Bienvenue sur ARCDSE",
    "firstLaunchDialogContent":
        "Vous avez installé ARCDSE Dental Clinic Management Software avec succès. Cependant, pour une meilleure expérience et une utilisation réelle, vous devrez configurer quelques éléments. Scannez le code QR ci-dessous pour commencer.",
    "newVersionDialogTitle": "Nouvelle version disponible",
    "newVersionDialogContent":
        "Une nouvelle version d'ARCDSE est disponible. Veuillez mettre à jour vers la dernière version pour obtenir la meilleure expérience. Scannez le code QR ci-dessous pour commencer.",
  };
}
